<?php
/**
 * First-activation content seeder.
 *
 * Creates the bundled Classic T-Shirt model (procedural GLB), its colors,
 * sizes, print areas (UV rects generated by tools/generate_tshirt_model.py),
 * the sample artwork library and a starter pricing rule set.
 *
 * @package TShirtDesigner
 */

declare( strict_types=1 );

namespace TShirtDesigner;

defined( 'ABSPATH' ) || exit;

final class Content_Seeder {

	public function __construct(
		private Database $db,
		private Model_Manager $models,
		private Color_Manager $colors,
		private Size_Manager $sizes,
		private Print_Area_Manager $print_areas,
		private Asset_Manager $assets,
		private Pricing_Engine $pricing
	) {}

	public function run(): void {
		if ( array() !== $this->models->all( false ) ) {
			return; // Already has content.
		}

		$model_id = $this->seed_model();
		$this->seed_colors( $model_id );
		$this->seed_sizes( $model_id );
		$this->seed_print_areas( $model_id );
		$this->seed_assets();
		$this->seed_pricing();
	}

	private function seed_model(): int {
		return $this->models->insert( array(
			'name'               => __( 'Classic T-Shirt', 'tshirt-designer' ),
			'slug'               => 'classic-tshirt',
			'description'        => __( 'Crew-neck short-sleeve t-shirt. Bundled 3D model with front, back and sleeve print areas.', 'tshirt-designer' ),
			'model_file_path'    => 'assets/models/classic-tshirt.glb',
			'preview_image_path' => 'assets/images/model-preview.png',
			'base_price'         => 350000.0,
			'is_active'          => 1,
			'sort_order'         => 0,
		) );
	}

	private function seed_colors( int $model_id ): void {
		$colors = array(
			array( __( 'White', 'tshirt-designer' ), '#FFFFFF', 0 ),
			array( __( 'Black', 'tshirt-designer' ), '#1E1E1E', 1 ),
			array( __( 'Red', 'tshirt-designer' ), '#C62828', 2 ),
			array( __( 'Navy', 'tshirt-designer' ), '#1A237E', 3 ),
			array( __( 'Green', 'tshirt-designer' ), '#1B5E20', 4 ),
			array( __( 'Yellow', 'tshirt-designer' ), '#F9A825', 5 ),
		);
		foreach ( $colors as $i => $color ) {
			$this->colors->insert( array(
				'model_id'   => $model_id,
				'name'       => $color[0],
				'hex'        => $color[1],
				'is_active'  => 1,
				'sort_order' => $i,
			) );
		}
	}

	private function seed_sizes( int $model_id ): void {
		$sizes = array(
			array( 'S', 0.0 ),
			array( 'M', 0.0 ),
			array( 'L', 0.0 ),
			array( 'XL', 20000.0 ),
			array( 'XXL', 40000.0 ),
			array( '3XL', 60000.0 ),
		);
		foreach ( $sizes as $i => $size ) {
			$this->sizes->insert( array(
				'model_id'       => $model_id,
				'name'           => $size[0],
				'price_modifier' => $size[1],
				'is_active'      => 1,
				'sort_order'     => $i,
			) );
		}
	}

	private function seed_print_areas( int $model_id ): void {
		// UV rects generated by tools/generate_tshirt_model.py (manifest.json).
		$areas = array(
			array(
				'name'          => __( 'Front', 'tshirt-designer' ),
				'type'          => 'front',
				'max_width_cm'  => 30.0,
				'max_height_cm' => 35.0,
				'position'      => array(
					'uv_rect' => array( 0.10577, 0.09286, 0.39423, 0.34286 ),
					'camera'  => array( 'azimuth' => 0, 'polar' => 78, 'distance' => 1.55 ),
				),
			),
			array(
				'name'          => __( 'Back', 'tshirt-designer' ),
				'type'          => 'back',
				'max_width_cm'  => 30.0,
				'max_height_cm' => 35.0,
				'position'      => array(
					'uv_rect' => array( 0.60577, 0.07857, 0.89423, 0.32857 ),
					'camera'  => array( 'azimuth' => 180, 'polar' => 78, 'distance' => 1.55 ),
				),
			),
			array(
				'name'          => __( 'Left sleeve', 'tshirt-designer' ),
				'type'          => 'left_sleeve',
				'max_width_cm'  => 10.0,
				'max_height_cm' => 20.0,
				'position'      => array(
					'uv_rect' => array( 0.189, 0.625, 0.311, 0.975 ),
					'camera'  => array( 'azimuth' => -80, 'polar' => 72, 'distance' => 1.5 ),
				),
			),
			array(
				'name'          => __( 'Right sleeve', 'tshirt-designer' ),
				'type'          => 'right_sleeve',
				'max_width_cm'  => 10.0,
				'max_height_cm' => 20.0,
				'position'      => array(
					'uv_rect' => array( 0.689, 0.625, 0.811, 0.975 ),
					'camera'  => array( 'azimuth' => 80, 'polar' => 72, 'distance' => 1.5 ),
				),
			),
		);
		foreach ( $areas as $i => $area ) {
			$this->print_areas->insert( array(
				'model_id'      => $model_id,
				'name'          => $area['name'],
				'area_type'     => $area['type'],
				'max_width_cm'  => $area['max_width_cm'],
				'max_height_cm' => $area['max_height_cm'],
				'position'      => $area['position'],
				'is_active'     => 1,
				'sort_order'    => $i,
			) );
		}
	}

	private function seed_assets(): void {
		$assets = array(
			array( 'Minimal Ring Logo', 'logo', 'assets/images/samples/logo-ring.png' ),
			array( 'Shield Emblem', 'logo', 'assets/images/samples/logo-shield.png' ),
			array( 'Legend Since 2024', 'text', 'assets/images/samples/text-legend.png' ),
			array( 'Number 01', 'text', 'assets/images/samples/text-number-01.png' ),
			array( 'Soccer Ball', 'sport', 'assets/images/samples/sport-soccer.png' ),
			array( 'Basketball', 'sport', 'assets/images/samples/sport-basketball.png' ),
			array( 'Cat Face', 'animal', 'assets/images/samples/animal-cat.png' ),
			array( 'Paw', 'animal', 'assets/images/samples/animal-paw.png' ),
			array( 'Mountains', 'nature', 'assets/images/samples/nature-mountains.png' ),
			array( 'Retro Sun', 'nature', 'assets/images/samples/nature-sun.png' ),
			array( 'Rocket', 'kids', 'assets/images/samples/kids-rocket.png' ),
			array( 'Smiling Star', 'kids', 'assets/images/samples/kids-smile-star.png' ),
			array( 'Lightning Bolt', 'fantasy', 'assets/images/samples/fantasy-bolt.png' ),
			array( 'Flame', 'fantasy', 'assets/images/samples/fantasy-flame.png' ),
			array( 'Crown', 'fantasy', 'assets/images/samples/fantasy-crown.png' ),
			array( 'Heart', 'other', 'assets/images/samples/other-heart.png' ),
			array( 'Skull', 'other', 'assets/images/samples/other-skull.png' ),
		);
		foreach ( $assets as $i => $asset ) {
			$this->assets->insert( array(
				'name'       => $asset[0],
				'category'   => $asset[1],
				'file_path'  => $asset[2],
				'is_active'  => 1,
				'sort_order' => $i,
			) );
		}
	}

	private function seed_pricing(): void {
		// Global size tiers (longest side of the artwork, cm).
		$tiers = array(
			array( 0.0, 10.0, 50000.0 ),
			array( 10.0, 20.0, 80000.0 ),
			array( 20.0, 30.0, 120000.0 ),
		);
		foreach ( $tiers as $i => $tier ) {
			$this->pricing->save_rule( array(
				'rule_type'    => Pricing_Engine::RULE_SIZE_TIER,
				'scope'        => 'global',
				'size_from_cm' => $tier[0],
				'size_to_cm'   => $tier[1],
				'price'        => $tier[2],
				'is_active'    => 1,
				'sort_order'   => $i,
			) );
		}

		// Extra charge for additional items in the same print area.
		$extras = array(
			array( 2, 20000.0 ),
			array( 3, 40000.0 ),
			array( 4, 60000.0 ),
		);
		foreach ( $extras as $i => $extra ) {
			$this->pricing->save_rule( array(
				'rule_type'   => Pricing_Engine::RULE_ITEM_EXTRA,
				'scope'       => 'global',
				'item_count'  => $extra[0],
				'price'       => $extra[1],
				'is_active'   => 1,
				'sort_order'  => $i,
			) );
		}
	}
}
